INSERT INTO `[dbprefix]class` VALUES ('1', '0', '电影', '1');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('2', '0', '连续剧', '2');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('3', '0', '动漫', '3');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('4', '0', '综艺', '4');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('5', '1', '动作片', '1');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('6', '1', '喜剧片', '2');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('7', '1', '爱情片', '3');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('8', '1', '科幻片', '4');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('9', '1', '恐怖片', '5');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('10', '1', '剧情片', '6');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('11', '1', '战争片', '7');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('12', '1', '悬疑片', '8');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('13', '1', '犯罪片', '9');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('14', '1', '惊悚片', '10');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('15', '1', '冒险片', '11');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('16', '1', '纪录片', '12');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('17', '1', '动画片', '13');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('18', '1', '微影视', '14');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('19', '1', '其他片', '15');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('20', '2', '国产剧', '1');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('21', '2', '港台剧', '2');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('22', '2', '日韩剧', '3');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('23', '2', '欧美剧', '4');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('24', '2', '其他剧', '5');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('25', '3', '国产动漫', '1');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('26', '3', '日韩动漫', '2');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('27', '3', '欧美动漫', '3');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('28', '3', '其他动漫', '4');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('29', '4', '大陆综艺', '1');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('30', '4', '日韩综艺', '2');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('31', '4', '港台综艺', '3');[yhcms]
INSERT INTO `[dbprefix]class` VALUES ('32', '4', '欧美综艺', '4');[yhcms]
INSERT INTO `[dbprefix]myopia_class` VALUES ('1', '电影解说', '0', '1');[yhcms]
INSERT INTO `[dbprefix]bbs_class` VALUES ('1', '观影感受', '', '0', '1');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('1', '无尽资源', 'wujinapi', '无尽资源', '', 'app', '0', '1');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('2', '速更资源', 'sugengzy', '速更资源', '', 'app', '0', '2');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('3', '鱼乐资源网', 'ylzy', '鱼乐资源网', '', 'app', '0', '3');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('4', '闪电资源网', 'shandianzy', '闪电资源网', '', 'app', '0', '4');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('5', 'KK资源', 'kkzy', 'KK资源网', '', 'app', '0', '5');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('6', '酷点资源', 'kudianzy', 'KK资源网', '', 'app', '0', '6');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('7', '想看资源', 'xkm3u8', '想看资源', '', 'app', '0', '7');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('8', '英皇官采', 'yhcms', '英皇官采', '//player.vipparsing.com/player?vid=', 'web', '0', '8');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('9', 'PPTV', 'pptv', 'PPTV', '//player.vipparsing.com/player?vid=', 'web', '0', '9');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('10', '乐视TV', 'letv', '乐视TV', '//player.vipparsing.com/player?vid=', 'web', '0', '10');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('11', '搜狐视频', 'sohu', '搜狐视频', '//player.vipparsing.com/player?vid=', 'web', '0', '11');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('12', '芒果TV', 'mgtv', '芒果TV解析', '//player.vipparsing.com/player?vid=', 'web', '0', '12');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('13', '优酷视频', 'youku', '优酷视频', '//player.vipparsing.com/player?vid=', 'web', '0', '13');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('14', 'CNTV', 'cctv', 'CNTV', '//player.vipparsing.com/player?vid=', 'web', '0', '14');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('15', '腾讯视频', 'qq', '腾讯视频', '//player.vipparsing.com/player?vid=', 'web', '0', '15');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('16', '爱奇艺', 'qiyi', '爱奇艺视频', '//player.vipparsing.com/player?vid=', 'web', '0', '16');[yhcms]
INSERT INTO `[dbprefix]player` VALUES ('17', '色猫资源', 'smzy', 'X资源', '', 'app', '0', '17');[yhcms]
INSERT INTO `[dbprefix]star_class` VALUES ('1', '男演员', '0', '1');[yhcms]
INSERT INTO `[dbprefix]star_class` VALUES ('2', '女演员', '0', '2');[yhcms]
INSERT INTO `[dbprefix]user_task` VALUES ('1', 'watch', '观看影片30分钟', '奖励50金币', '1', '50', '1800', '1');[yhcms]
INSERT INTO `[dbprefix]user_task` VALUES ('2', 'watch', '观看影片1小时', '奖励200金币', '1', '200', '3600', '2');[yhcms]
INSERT INTO `[dbprefix]user_task` VALUES ('3', 'share', '邀请好友一起看', '每次奖励5金币，每日上限10次', '10', '5', '0', '6');[yhcms]
INSERT INTO `[dbprefix]user_task` VALUES ('4', 'watch', '观看影片2小时', '奖励金币500', '1', '500', '7200', '4');[yhcms]
INSERT INTO `[dbprefix]links` VALUES ('1', '英皇CMS', 'http://www.yhcms.cc/')